name: Build CoreProtect Plugin

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: '3.9.6'
        
    - name: Modify plugin.yml
      run: |
        sed -i 's/branch: ${project.branch}/branch: development/' src/main/resources/plugin.yml
        
    - name: Build with Maven
      run: mvn clean install
      
    - name: Generate build timestamp
      id: timestamp
      run: |
        echo "timestamp=$(date +'%Y.%m.%d.%H%M%S')" >> $GITHUB_OUTPUT
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: build-${{ steps.timestamp.outputs.timestamp }}
        name: "CoreProtect ${{ steps.timestamp.outputs.timestamp }}"
        body: "Automatic build from main branch"
        files: target/CoreProtect-*.jar
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
